### ISSUE TITLE
.sourceResource.dataProvider

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/country_music_hall_of_fame#1]
I believe the .sourceResource.dataProvider should be _Country Music Hall of Fame and Museum_. In the MODS feed, I'm seeing <recordContentSource>Country Music Hall of Fame</recordContentSource>. It's just missing _and Museum_ at the end. I hope this is an easy fix.

**Comment by markpbaggett** [comment]
Sorry.  I grabbed what was before the trademark. Let me update this and push.

**Comment by carolynfrunyon** [comment]
Thanks Mark!

**Comment by markpbaggett** [comment]
@carolynfrunyon, this should be fixed although i stripped the trademark symbol.

**Comment by carolynfrunyon** [comment]
I think it looks good!
